// Command gencode-handwritten emits commands/handwritten/z_builtin_table_gen.go from testdata JSON:
// static []types.Command literals (TS-style table), not embedded JSON strings.
//
//	go run ./cmd/gencode-handwritten
//
// Run from the goc module root after updating commands/testdata/*.json.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"

	"goc/types"
	"goc/utils"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	td := filepath.Join(root, "commands", "testdata")
	handwrittenDir := filepath.Join(root, "commands", "handwritten")
	defPath := filepath.Join(td, "builtin_commands_default.json")
	intPath := filepath.Join(td, "internal_only_commands.json")
	outPath := filepath.Join(handwrittenDir, "z_builtin_table_gen.go")

	defRaw, err := os.ReadFile(defPath)
	if err != nil {
		log.Fatal(err)
	}
	intRaw, err := os.ReadFile(intPath)
	if err != nil {
		log.Fatal(err)
	}
	var def, internal []types.Command
	if err := json.Unmarshal(defRaw, &def); err != nil {
		log.Fatal(err)
	}
	if err := json.Unmarshal(intRaw, &internal); err != nil {
		log.Fatal(err)
	}

	needJSON := false
	needUtils := false
	for _, c := range def {
		if len(c.PluginInfo) > 0 || len(c.Hooks) > 0 {
			needJSON = true
		}
		if c.Effort != nil {
			needUtils = true
		}
	}
	for _, c := range internal {
		if len(c.PluginInfo) > 0 || len(c.Hooks) > 0 {
			needJSON = true
		}
		if c.Effort != nil {
			needUtils = true
		}
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gencode-handwritten; DO NOT EDIT.\n\n")
	buf.WriteString("package handwritten\n\n")
	buf.WriteString("import (\n")
	if needJSON {
		buf.WriteString("\t\"encoding/json\"\n\n")
	}
	buf.WriteString("\t\"goc/types\"\n")
	if needUtils {
		buf.WriteString("\t\"goc/utils\"\n")
	}
	buf.WriteString(")\n\n")
	buf.WriteString("// builtinDefaultCommandsTable is the frozen COMMANDS() core (before runtime spreads).\n")
	buf.WriteString("// Refresh: go run ./cmd/gencode-handwritten (from module root).\n")
	buf.WriteString("var builtinDefaultCommandsTable = ")
	emitCommandSlice(&buf, def)
	buf.WriteString("\n\n// internalOnlyCommandsTable mirrors TS INTERNAL_ONLY_COMMANDS listing metadata.\n")
	buf.WriteString("var internalOnlyCommandsTable = ")
	emitCommandSlice(&buf, internal)
	buf.WriteString("\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", buf.String())
		log.Fatal(err)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %s\n", outPath)
}

func emitCommandSlice(buf *bytes.Buffer, cmds []types.Command) {
	buf.WriteString("[]types.Command{\n")
	for _, c := range cmds {
		emitOneCommand(buf, c)
	}
	buf.WriteString("}")
}

func emitOneCommand(buf *bytes.Buffer, c types.Command) {
	buf.WriteString("\t{\n")
	buf.WriteString("\t\tCommandBase: types.CommandBase{\n")
	fmt.Fprintf(buf, "\t\t\tName: %q,\n", c.Name)
	fmt.Fprintf(buf, "\t\t\tDescription: %q,\n", c.Description)
	if len(c.Availability) > 0 {
		buf.WriteString("\t\t\tAvailability: []types.CommandAvailability{")
		for i, a := range c.Availability {
			if i > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(availabilityConst(a))
		}
		buf.WriteString("},\n")
	}
	emitBoolPtr(buf, "\t\t\t", "HasUserSpecifiedDescription", c.HasUserSpecifiedDescription)
	emitBoolPtr(buf, "\t\t\t", "IsHidden", c.IsHidden)
	if len(c.Aliases) > 0 {
		buf.WriteString("\t\t\tAliases: []string{")
		for i, a := range c.Aliases {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(buf, "%q", a)
		}
		buf.WriteString("},\n")
	}
	emitBoolPtr(buf, "\t\t\t", "IsMcp", c.IsMcp)
	emitStrPtr(buf, "\t\t\t", "ArgumentHint", derefStr(c.ArgumentHint), c.ArgumentHint != nil)
	emitStrPtr(buf, "\t\t\t", "WhenToUse", derefStr(c.WhenToUse), c.WhenToUse != nil)
	emitStrPtr(buf, "\t\t\t", "Version", derefStr(c.Version), c.Version != nil)
	emitBoolPtr(buf, "\t\t\t", "DisableModelInvocation", c.DisableModelInvocation)
	emitBoolPtr(buf, "\t\t\t", "UserInvocable", c.UserInvocable)
	emitStrPtr(buf, "\t\t\t", "LoadedFrom", derefStr(c.LoadedFrom), c.LoadedFrom != nil)
	emitStrPtr(buf, "\t\t\t", "Kind", derefStr(c.Kind), c.Kind != nil)
	emitBoolPtr(buf, "\t\t\t", "Immediate", c.Immediate)
	emitBoolPtr(buf, "\t\t\t", "IsSensitive", c.IsSensitive)
	buf.WriteString("\t\t},\n")
	fmt.Fprintf(buf, "\t\tType: %q,\n", c.Type)
	emitStrPtr(buf, "\t\t", "ProgressMessage", derefStr(c.ProgressMessage), c.ProgressMessage != nil)
	emitIntPtr(buf, "\t\t", "ContentLength", c.ContentLength)
	if len(c.ArgNames) > 0 {
		buf.WriteString("\t\tArgNames: []string{")
		for i, a := range c.ArgNames {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(buf, "%q", a)
		}
		buf.WriteString("},\n")
	}
	if len(c.AllowedTools) > 0 {
		buf.WriteString("\t\tAllowedTools: []string{")
		for i, a := range c.AllowedTools {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(buf, "%q", a)
		}
		buf.WriteString("},\n")
	}
	emitStrPtr(buf, "\t\t", "Model", derefStr(c.Model), c.Model != nil)
	emitStrPtr(buf, "\t\t", "Source", derefStr(c.Source), c.Source != nil)
	if len(c.PluginInfo) > 0 {
		fmt.Fprintf(buf, "\t\tPluginInfo: json.RawMessage(%q),\n", string(c.PluginInfo))
	}
	if len(c.Hooks) > 0 {
		fmt.Fprintf(buf, "\t\tHooks: json.RawMessage(%q),\n", string(c.Hooks))
	}
	emitBoolPtr(buf, "\t\t", "DisableNonInteractive", c.DisableNonInteractive)
	emitStrPtr(buf, "\t\t", "SkillRoot", derefStr(c.SkillRoot), c.SkillRoot != nil)
	emitStrPtr(buf, "\t\t", "Context", derefStr(c.Context), c.Context != nil)
	emitStrPtr(buf, "\t\t", "Agent", derefStr(c.Agent), c.Agent != nil)
	if c.Effort != nil {
		emitEffort(buf, "\t\t", c.Effort)
	}
	if len(c.Paths) > 0 {
		buf.WriteString("\t\tPaths: []string{")
		for i, p := range c.Paths {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(buf, "%q", p)
		}
		buf.WriteString("},\n")
	}
	emitBoolPtr(buf, "\t\t", "SupportsNonInteractive", c.SupportsNonInteractive)
	buf.WriteString("\t},\n")
}

func emitEffort(buf *bytes.Buffer, indent string, e *utils.EffortValue) {
	if e == nil {
		return
	}
	lvl, ok := e.Level()
	if ok {
		fmt.Fprintf(buf, "%sEffort: effortPtr(utils.EffortFromLevel(utils.%s)),\n", indent, effortConst(lvl))
		return
	}
	n, ok := e.Number()
	if ok {
		fmt.Fprintf(buf, "%sEffort: effortPtr(utils.EffortFromNumber(%g)),\n", indent, n)
	}
}

func effortConst(l utils.EffortLevel) string {
	switch l {
	case utils.EffortLow:
		return "EffortLow"
	case utils.EffortMedium:
		return "EffortMedium"
	case utils.EffortHigh:
		return "EffortHigh"
	case utils.EffortMax:
		return "EffortMax"
	default:
		// utils.EffortFromLevel(utils.EffortLevel("..."))
		return fmt.Sprintf("EffortLevel(%q)", string(l))
	}
}

func availabilityConst(a types.CommandAvailability) string {
	switch a {
	case types.CommandAvailabilityClaudeAI:
		return "types.CommandAvailabilityClaudeAI"
	case types.CommandAvailabilityConsole:
		return "types.CommandAvailabilityConsole"
	default:
		return fmt.Sprintf("types.CommandAvailability(%q)", string(a))
	}
}

func derefStr(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

func emitStrPtr(buf *bytes.Buffer, indent, field, val string, include bool) {
	if !include {
		return
	}
	fmt.Fprintf(buf, "%s%s: ptrStr(%q),\n", indent, field, val)
}

func emitBoolPtr(buf *bytes.Buffer, indent, field string, p *bool) {
	if p == nil {
		return
	}
	fmt.Fprintf(buf, "%s%s: ptrBool(%v),\n", indent, field, *p)
}

func emitIntPtr(buf *bytes.Buffer, indent, field string, p *int) {
	if p == nil {
		return
	}
	fmt.Fprintf(buf, "%s%s: ptrInt(%d),\n", indent, field, *p)
}
