// Command gencode-handwritten embeds JSON snapshots as Go raw string constants for package handwritten.
//
//	go run ./cmd/gencode-handwritten
//
// Run from the goc module directory after updating testdata/*.json.
package main

import (
	"log"
	"os"
	"path/filepath"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	td := filepath.Join(root, "commands", "testdata")
	defPath := filepath.Join(td, "builtin_commands_default.json")
	intPath := filepath.Join(td, "internal_only_commands.json")
	def, err := os.ReadFile(defPath)
	if err != nil {
		log.Fatal(err)
	}
	internal, err := os.ReadFile(intPath)
	if err != nil {
		log.Fatal(err)
	}
	outPath := filepath.Join(root, "commands", "handwritten", "z_jsondata.go")
	f, err := os.Create(outPath)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	w := func(s string) {
		if _, err := f.WriteString(s); err != nil {
			log.Fatal(err)
		}
	}
	w("// Code generated by gencode-handwritten; DO NOT EDIT.\n\n")
	w("package handwritten\n\n")
	w("const builtinCommandsDefaultJSON = `")
	if _, err := f.Write(def); err != nil {
		log.Fatal(err)
	}
	w("`\n\nconst internalOnlyCommandsJSON = `")
	if _, err := f.Write(internal); err != nil {
		log.Fatal(err)
	}
	w("`\n")
	if err := f.Close(); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %s\n", outPath)
}
