package query

import (
	"encoding/json"
)

// anthropicToolsWireToOpenAI mirrors src/api-client/openai/convertTools.ts anthropicToolsToOpenAI
// plus the advisor/computer filter from src/api-client/openai/index.ts standardTools.
func anthropicToolsWireToOpenAI(toolsJSON json.RawMessage) ([]map[string]any, error) {
	if len(toolsJSON) == 0 || string(toolsJSON) == "null" {
		return nil, nil
	}
	var arr []json.RawMessage
	if err := json.Unmarshal(toolsJSON, &arr); err != nil {
		return nil, err
	}
	var out []map[string]any
	for _, raw := range arr {
		var t map[string]any
		if err := json.Unmarshal(raw, &t); err != nil {
			continue
		}
		typ, _ := t["type"].(string)
		if typ == "advisor_20260301" || typ == "computer_20250124" {
			continue
		}
		if typ == "server" {
			continue
		}
		name, _ := t["name"].(string)
		desc, _ := t["description"].(string)
		params := t["input_schema"]
		if params == nil {
			params = map[string]any{"type": "object", "properties": map[string]any{}}
		}
		if schema, ok := params.(map[string]any); ok {
			params = sanitizeJsonSchema(schema)
		}
		out = append(out, map[string]any{
			"type": "function",
			"function": map[string]any{
				"name":        name,
				"description": desc,
				"parameters":  params,
			},
		})
	}
	return out, nil
}

// sanitizeJsonSchema mirrors src/services/api/openai/convertTools.ts sanitizeJsonSchema.
// Strips $schema and propertyNames (not generated by Zod/TS side), converts const→enum,
// and recursively processes nested schemas for OpenAI-compatible provider compatibility.
func sanitizeJsonSchema(schema map[string]any) map[string]any {
	if schema == nil {
		return nil
	}

	// Strip $schema — OpenAI-compatible providers don't expect it inside function parameters.
	delete(schema, "$schema")

	// Strip propertyNames — Zod/TS doesn't generate it; some providers reject it.
	delete(schema, "propertyNames")

	// Convert const → enum: [value] (semantically equivalent, more widely supported).
	if c, ok := schema["const"]; ok {
		schema["enum"] = []any{c}
		delete(schema, "const")
	}

	// Recursively process object-keys (properties, definitions, $defs, patternProperties).
	for _, key := range []string{"properties", "definitions", "$defs", "patternProperties"} {
		if nested, ok := schema[key].(map[string]any); ok {
			sanitized := make(map[string]any, len(nested))
			for k, v := range nested {
				if m, ok := v.(map[string]any); ok {
					sanitized[k] = sanitizeJsonSchema(m)
				} else {
					sanitized[k] = v
				}
			}
			schema[key] = sanitized
		}
	}

	// Recursively process single-schema keys.
	for _, key := range []string{"items", "additionalProperties", "not", "if", "then", "else", "contains"} {
		if nested, ok := schema[key].(map[string]any); ok {
			schema[key] = sanitizeJsonSchema(nested)
		}
	}

	// Recursively process array-of-schemas keys.
	for _, key := range []string{"anyOf", "oneOf", "allOf"} {
		if arr, ok := schema[key].([]any); ok {
			sanitized := make([]any, len(arr))
			for i, item := range arr {
				if m, ok := item.(map[string]any); ok {
					sanitized[i] = sanitizeJsonSchema(m)
				} else {
					sanitized[i] = item
				}
			}
			schema[key] = sanitized
		}
	}

	return schema
}
