// Command gen-tool-parity reads tools/toolparity/catalog.json and writes tools/toolparity/TS_GO_TOOL_PARITY.md.
//
// Usage:
//
//	go run ./cmd/gen-tool-parity
//
// Finds the module root by walking up until go.mod is found (cwd may be any subdirectory).
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

type catalog struct {
	TSAnchorFile   string            `json:"ts_anchor_file"`
	TSAnchorSymbol string            `json:"ts_anchor_symbol"`
	GoAnchorFile   string            `json:"go_anchor_file"`
	GoAnchorNote   string            `json:"go_anchor_note"`
	StatusLegend   map[string]string `json:"status_legend"`
	Entries        []entry           `json:"entries"`
}

type entry struct {
	Name       string   `json:"name"`
	Aliases    []string `json:"aliases,omitempty"`
	TSPresence string   `json:"ts_presence"`
	TSNote     string   `json:"ts_note,omitempty"`
	GoStatus   string   `json:"go_status"`
	GoLocation string   `json:"go_location"`
}

func findModuleRoot(start string) (string, error) {
	dir := start
	for i := 0; i < 32; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", fmt.Errorf("go.mod not found from %s", start)
}

func main() {
	wd, err := os.Getwd()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	modRoot, err := findModuleRoot(wd)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-tool-parity:", err)
		os.Exit(1)
	}

	catPath := filepath.Join(modRoot, "tools", "toolparity", "catalog.json")
	raw, err := os.ReadFile(catPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	var c catalog
	if err := json.Unmarshal(raw, &c); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	var b bytes.Buffer
	bt := "```"
	fmt.Fprintf(&b, "# TS vs Go built-in tool parity\n\n")
	fmt.Fprintf(&b, "**Do not edit this file by hand.** Regenerate from the `claude-go` module root:\n\n")
	fmt.Fprintf(&b, "%sbash\n", bt)
	fmt.Fprintf(&b, "go run ./cmd/gen-tool-parity\n")
	fmt.Fprintf(&b, "%s\n\n", bt)
	fmt.Fprintf(&b, "- **TS source:** [%s](%s) `%s`\n", c.TSAnchorFile, c.TSAnchorFile, c.TSAnchorSymbol)
	fmt.Fprintf(&b, "- **Go anchor:** [%s](%s) — %s\n", c.GoAnchorFile, c.GoAnchorFile, c.GoAnchorNote)
	fmt.Fprintf(&b, "- **Generated:** %s\n\n", time.Now().UTC().Format(time.RFC3339))

	b.WriteString("## Status legend\n\n")
	keys := make([]string, 0, len(c.StatusLegend))
	for k := range c.StatusLegend {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&b, "- **%s:** %s\n", k, c.StatusLegend[k])
	}
	b.WriteString("\n## Table\n\n")
	b.WriteString("| Tool | Aliases | TS presence | TS note | Go status | Go location |\n")
	b.WriteString("|------|---------|-------------|---------|-----------|-------------|\n")

	counts := map[string]int{}
	for _, e := range c.Entries {
		counts[e.GoStatus]++
		ac := "—"
		if len(e.Aliases) > 0 {
			ac = strings.Join(e.Aliases, ", ")
		}
		note := "—"
		if strings.TrimSpace(e.TSNote) != "" {
			note = strings.ReplaceAll(e.TSNote, "|", "\\|")
		}
		gl := e.GoLocation
		if gl == "" {
			gl = "—"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s |\n",
			strings.ReplaceAll(e.Name, "|", "\\|"),
			strings.ReplaceAll(ac, "|", "\\|"),
			strings.ReplaceAll(e.TSPresence, "|", "\\|"),
			note,
			e.GoStatus,
			strings.ReplaceAll(gl, "|", "\\|"),
		)
	}

	b.WriteString("\n## Counts (this catalog)\n\n")
	b.WriteString("| Go status | Count |\n|-----------|------:|\n")
	order := []string{"full", "partial", "stub", "none"}
	seen := map[string]bool{}
	for _, k := range order {
		if n, ok := counts[k]; ok {
			fmt.Fprintf(&b, "| %s | %d |\n", k, n)
			seen[k] = true
		}
	}
	var rest []string
	for k := range counts {
		if !seen[k] {
			rest = append(rest, k)
		}
	}
	sort.Strings(rest)
	for _, k := range rest {
		fmt.Fprintf(&b, "| %s | %d |\n", k, counts[k])
	}

	outPath := filepath.Join(modRoot, "tools", "toolparity", "TS_GO_TOOL_PARITY.md")
	if err := os.WriteFile(outPath, b.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("wrote", outPath)
}
