// Code generated by cmd/gencode-handwritten; DO NOT EDIT.

package handwritten

import (
	"goc/types"
)

// builtinDefaultCommandsTable is the frozen COMMANDS() core (before runtime spreads).
// Refresh: go run ./cmd/gencode-handwritten (from module root).
var builtinDefaultCommandsTable = []types.Command{
	{
		CommandBase: types.CommandBase{
			Name:         "add-dir",
			Description:  "Add a new working directory",
			ArgumentHint: ptrStr("<path>"),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "advisor",
			Description:  "Configure the advisor model",
			IsHidden:     ptrBool(true),
			ArgumentHint: ptrStr("[<model>|off]"),
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(true),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "agents",
			Description: "Manage agent configurations",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "branch",
			Description:  "Create a branch of the current conversation at this point",
			Aliases:      []string{"fork"},
			ArgumentHint: ptrStr("[name]"),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "btw",
			Description:  "Ask a quick side question without interrupting the main conversation",
			ArgumentHint: ptrStr("<question>"),
			Immediate:    ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "chrome",
			Description: "Claude in Chrome (Beta) settings",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "clear",
			Description: "Clear conversation history and free up context",
			Aliases:     []string{"reset", "new"},
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(false),
	},
	{
		CommandBase: types.CommandBase{
			Name:         "color",
			Description:  "Set the prompt bar color for this session",
			ArgumentHint: ptrStr("<color|default>"),
			Immediate:    ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "compact",
			Description:  "Clear conversation history but keep a summary in context. Optional: /compact [instructions for summarization]",
			ArgumentHint: ptrStr("<optional custom summarization instructions>"),
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(true),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "config",
			Description: "Open config panel",
			Aliases:     []string{"settings"},
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "copy",
			Description: "Copy Claude's last response to clipboard (or /copy N for the Nth-latest)",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "desktop",
			Description:  "Continue the current session in Claude Desktop",
			Availability: []types.CommandAvailability{types.CommandAvailabilityClaudeAI},
			IsHidden:     ptrBool(false),
			Aliases:      []string{"app"},
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "context",
			Description: "Visualize current context usage as a colored grid",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "context",
			Description: "Show current context usage",
			IsHidden:    ptrBool(false),
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(true),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "cost",
			Description: "Show the total cost and duration of the current session",
			IsHidden:    ptrBool(false),
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(true),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "diff",
			Description: "View uncommitted changes and per-turn diffs",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "doctor",
			Description: "Diagnose and verify your Claude Code installation and settings",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "effort",
			Description:  "Set effort level for model usage",
			ArgumentHint: ptrStr("[low|medium|high|max|auto]"),
			Immediate:    ptrBool(false),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "exit",
			Description: "Exit the REPL",
			Aliases:     []string{"quit"},
			Immediate:   ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "fast",
			Description:  "Toggle fast mode (Opus 4.6 only)",
			Availability: []types.CommandAvailability{types.CommandAvailabilityClaudeAI, types.CommandAvailabilityConsole},
			IsHidden:     ptrBool(true),
			ArgumentHint: ptrStr("[on|off]"),
			Immediate:    ptrBool(false),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "files",
			Description: "List all files currently in context",
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(true),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "heapdump",
			Description: "Dump the JS heap to ~/Desktop",
			IsHidden:    ptrBool(true),
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(true),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "help",
			Description: "Show help and available commands",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "ide",
			Description:  "Manage IDE integrations and show status",
			ArgumentHint: ptrStr("[open]"),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "init",
			Description: "Initialize a new CLAUDE.md file with codebase documentation",
		},
		Type:            "prompt",
		ProgressMessage: ptrStr("analyzing your codebase"),
		ContentLength:   ptrInt(0),
		Source:          ptrStr("builtin"),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "keybindings",
			Description: "Open or create your keybindings configuration file",
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(false),
	},
	{
		CommandBase: types.CommandBase{
			Name:         "install-github-app",
			Description:  "Set up Claude GitHub Actions for a repository",
			Availability: []types.CommandAvailability{types.CommandAvailabilityClaudeAI, types.CommandAvailabilityConsole},
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "install-slack-app",
			Description:  "Install the Claude Slack app",
			Availability: []types.CommandAvailability{types.CommandAvailabilityClaudeAI},
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(false),
	},
	{
		CommandBase: types.CommandBase{
			Name:         "mcp",
			Description:  "Manage MCP servers",
			ArgumentHint: ptrStr("[enable|disable [server-name]]"),
			Immediate:    ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "memory",
			Description: "Edit Claude memory files",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "mobile",
			Description: "Show QR code to download the Claude mobile app",
			Aliases:     []string{"ios", "android"},
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "model",
			Description:  "Set the AI model for Claude Code (currently deepseek-chat)",
			ArgumentHint: ptrStr("[model]"),
			Immediate:    ptrBool(false),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "output-style",
			Description: "Deprecated: use /config to change output style",
			IsHidden:    ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "remote-env",
			Description: "Configure the default remote environment for teleport sessions",
			IsHidden:    ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "plugin",
			Description: "Manage Claude Code plugins",
			Aliases:     []string{"plugins", "marketplace"},
			Immediate:   ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "pr-comments",
			Description: "Get comments from a GitHub pull request",
		},
		Type:            "prompt",
		ProgressMessage: ptrStr("fetching PR comments"),
		ContentLength:   ptrInt(0),
		Source:          ptrStr("builtin"),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "release-notes",
			Description: "View release notes",
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(true),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "reload-plugins",
			Description: "Activate pending plugin changes in the current session",
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(false),
	},
	{
		CommandBase: types.CommandBase{
			Name:         "rename",
			Description:  "Rename the current conversation",
			ArgumentHint: ptrStr("[name]"),
			Immediate:    ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "resume",
			Description:  "Resume a previous conversation",
			Aliases:      []string{"continue"},
			ArgumentHint: ptrStr("[conversation id or search term]"),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "session",
			Description: "Show remote session URL and QR code",
			IsHidden:    ptrBool(true),
			Aliases:     []string{"remote"},
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "skills",
			Description: "List available skills",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stats",
			Description: "Show your Claude Code usage statistics and activity",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "status",
			Description: "Show Claude Code status including version, model, account, API connectivity, and tool statuses",
			Immediate:   ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "statusline",
			Description: "Set up Claude Code's status line UI",
		},
		Type:                  "prompt",
		ProgressMessage:       ptrStr("setting up statusLine"),
		ContentLength:         ptrInt(0),
		AllowedTools:          []string{"Agent", "Read(~/**)", "Edit(~/.claude/settings.json)"},
		Source:                ptrStr("builtin"),
		DisableNonInteractive: ptrBool(true),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stickers",
			Description: "Order Claude Code stickers",
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(false),
	},
	{
		CommandBase: types.CommandBase{
			Name:         "tag",
			Description:  "Toggle a searchable tag on the current session",
			ArgumentHint: ptrStr("<tag-name>"),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "theme",
			Description: "Change the theme",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "feedback",
			Description:  "Submit feedback about Claude Code",
			Aliases:      []string{"bug"},
			ArgumentHint: ptrStr("[report]"),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "review",
			Description: "Review a pull request",
		},
		Type:            "prompt",
		ProgressMessage: ptrStr("reviewing pull request"),
		ContentLength:   ptrInt(0),
		Source:          ptrStr("builtin"),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "ultrareview",
			Description: "~10–20 min · Finds and verifies bugs in your branch. Runs in Claude Code on the web. See https://code.claude.com/docs/en/claude-code-on-the-web",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "rewind",
			Description:  "Restore the code and/or conversation to a previous point",
			Aliases:      []string{"checkpoint"},
			ArgumentHint: ptrStr(""),
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(false),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "security-review",
			Description: "Complete a security review of the pending changes on the current branch",
		},
		Type:            "prompt",
		ProgressMessage: ptrStr("analyzing code changes for security risks"),
		ContentLength:   ptrInt(0),
		Source:          ptrStr("builtin"),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "terminal-setup",
			Description: "Install Shift+Enter key binding for newlines",
			IsHidden:    ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "upgrade",
			Description:  "Upgrade to Max for higher rate limits and more Opus",
			Availability: []types.CommandAvailability{types.CommandAvailabilityClaudeAI},
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "extra-usage",
			Description: "Configure extra usage to keep working when limits are hit",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "extra-usage",
			Description: "Configure extra usage to keep working when limits are hit",
			IsHidden:    ptrBool(false),
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(true),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "rate-limit-options",
			Description: "Show options when rate limit is reached",
			IsHidden:    ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "usage",
			Description:  "Show plan usage limits",
			Availability: []types.CommandAvailability{types.CommandAvailabilityClaudeAI},
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "insights",
			Description: "Generate a report analyzing your Claude Code sessions",
		},
		Type:            "prompt",
		ProgressMessage: ptrStr("analyzing your sessions"),
		ContentLength:   ptrInt(0),
		Source:          ptrStr("builtin"),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "vim",
			Description: "Toggle between Vim and Normal editing modes",
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(false),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "think-back",
			Description: "Your 2025 Claude Code Year in Review",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "thinkback-play",
			Description: "Play the thinkback animation",
			IsHidden:    ptrBool(true),
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(false),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "permissions",
			Description: "Manage allow & deny tool permission rules",
			Aliases:     []string{"allowed-tools"},
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "plan",
			Description:  "Enable plan mode or view the current session plan",
			ArgumentHint: ptrStr("[open|<description>]"),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "privacy-settings",
			Description: "View and update your privacy settings",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "hooks",
			Description: "View hook configurations for tool events",
			Immediate:   ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "export",
			Description:  "Export the current conversation to a file or clipboard",
			ArgumentHint: ptrStr("[filename]"),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:         "sandbox",
			Description:  "◯ sandbox disabled (⏎ to configure)",
			IsHidden:     ptrBool(false),
			ArgumentHint: ptrStr("exclude \"command pattern\""),
			Immediate:    ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "logout",
			Description: "Sign out from your Anthropic account",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "login",
			Description: "Sign in with your Anthropic account",
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "passes",
			Description: "Share a free week of Claude Code with friends",
			IsHidden:    ptrBool(true),
		},
		Type: "local-jsx",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "tasks",
			Description: "List and manage background tasks",
			Aliases:     []string{"bashes"},
		},
		Type: "local-jsx",
	},
}

// internalOnlyCommandsTable mirrors TS INTERNAL_ONLY_COMMANDS listing metadata.
var internalOnlyCommandsTable = []types.Command{
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "commit",
			Description: "Create a git commit",
		},
		Type:            "prompt",
		ProgressMessage: ptrStr("creating commit"),
		ContentLength:   ptrInt(0),
		AllowedTools:    []string{"Bash(git add:*)", "Bash(git status:*)", "Bash(git commit:*)"},
		Source:          ptrStr("builtin"),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "commit-push-pr",
			Description: "Commit, push, and open a PR",
		},
		Type:            "prompt",
		ProgressMessage: ptrStr("creating commit and PR"),
		ContentLength:   ptrInt(3360),
		AllowedTools:    []string{"Bash(git checkout --branch:*)", "Bash(git checkout -b:*)", "Bash(git add:*)", "Bash(git status:*)", "Bash(git push:*)", "Bash(git commit:*)", "Bash(gh pr create:*)", "Bash(gh pr edit:*)", "Bash(gh pr view:*)", "Bash(gh pr merge:*)", "ToolSearch", "mcp__slack__send_message", "mcp__claude_ai_Slack__slack_send_message"},
		Source:          ptrStr("builtin"),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "init-verifiers",
			Description: "Create verifier skill(s) for automated verification of code changes",
		},
		Type:            "prompt",
		ProgressMessage: ptrStr("analyzing your project and creating verifier skills"),
		ContentLength:   ptrInt(0),
		Source:          ptrStr("builtin"),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "bridge-kick",
			Description: "Inject bridge failure states for manual recovery testing",
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(false),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "version",
			Description: "Print the version this session is running (not what autoupdate downloaded)",
		},
		Type:                   "local",
		SupportsNonInteractive: ptrBool(true),
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "agents-platform",
			Description: "",
		},
		Type: "local",
	},
	{
		CommandBase: types.CommandBase{
			Name:        "stub",
			Description: "",
			IsHidden:    ptrBool(true),
		},
		Type: "",
	},
}
