// Code generated by gencode-handwritten; DO NOT EDIT.

package handwritten

const builtinCommandsDefaultJSON = `[
  {
    "type": "local-jsx",
    "name": "add-dir",
    "description": "Add a new working directory",
    "argumentHint": "<path>"
  },
  {
    "type": "local",
    "name": "advisor",
    "description": "Configure the advisor model",
    "argumentHint": "[<model>|off]",
    "isHidden": true,
    "supportsNonInteractive": true
  },
  {
    "type": "local-jsx",
    "name": "agents",
    "description": "Manage agent configurations"
  },
  {
    "type": "local-jsx",
    "name": "branch",
    "aliases": [
      "fork"
    ],
    "description": "Create a branch of the current conversation at this point",
    "argumentHint": "[name]"
  },
  {
    "type": "local-jsx",
    "name": "btw",
    "description": "Ask a quick side question without interrupting the main conversation",
    "immediate": true,
    "argumentHint": "<question>"
  },
  {
    "name": "chrome",
    "description": "Claude in Chrome (Beta) settings",
    "availability": [],
    "type": "local-jsx"
  },
  {
    "type": "local",
    "name": "clear",
    "description": "Clear conversation history and free up context",
    "aliases": [
      "reset",
      "new"
    ],
    "supportsNonInteractive": false
  },
  {
    "type": "local-jsx",
    "name": "color",
    "description": "Set the prompt bar color for this session",
    "immediate": true,
    "argumentHint": "<color|default>"
  },
  {
    "type": "local",
    "name": "compact",
    "description": "Clear conversation history but keep a summary in context. Optional: /compact [instructions for summarization]",
    "supportsNonInteractive": true,
    "argumentHint": "<optional custom summarization instructions>"
  },
  {
    "aliases": [
      "settings"
    ],
    "type": "local-jsx",
    "name": "config",
    "description": "Open config panel"
  },
  {
    "type": "local-jsx",
    "name": "copy",
    "description": "Copy Claude's last response to clipboard (or /copy N for the Nth-latest)"
  },
  {
    "type": "local-jsx",
    "name": "desktop",
    "aliases": [
      "app"
    ],
    "description": "Continue the current session in Claude Desktop",
    "availability": [
      "claude-ai"
    ],
    "isHidden": false
  },
  {
    "name": "context",
    "description": "Visualize current context usage as a colored grid",
    "type": "local-jsx"
  },
  {
    "type": "local",
    "name": "context",
    "supportsNonInteractive": true,
    "description": "Show current context usage",
    "isHidden": false
  },
  {
    "type": "local",
    "name": "cost",
    "description": "Show the total cost and duration of the current session",
    "isHidden": false,
    "supportsNonInteractive": true
  },
  {
    "type": "local-jsx",
    "name": "diff",
    "description": "View uncommitted changes and per-turn diffs"
  },
  {
    "name": "doctor",
    "description": "Diagnose and verify your Claude Code installation and settings",
    "type": "local-jsx"
  },
  {
    "type": "local-jsx",
    "name": "effort",
    "description": "Set effort level for model usage",
    "argumentHint": "[low|medium|high|max|auto]",
    "immediate": false
  },
  {
    "type": "local-jsx",
    "name": "exit",
    "aliases": [
      "quit"
    ],
    "description": "Exit the REPL",
    "immediate": true
  },
  {
    "type": "local-jsx",
    "name": "fast",
    "description": "Toggle fast mode (Opus 4.6 only)",
    "availability": [
      "claude-ai",
      "console"
    ],
    "isHidden": true,
    "argumentHint": "[on|off]",
    "immediate": false
  },
  {
    "type": "local",
    "name": "files",
    "description": "List all files currently in context",
    "supportsNonInteractive": true
  },
  {
    "type": "local",
    "name": "heapdump",
    "description": "Dump the JS heap to ~/Desktop",
    "isHidden": true,
    "supportsNonInteractive": true
  },
  {
    "type": "local-jsx",
    "name": "help",
    "description": "Show help and available commands"
  },
  {
    "type": "local-jsx",
    "name": "ide",
    "description": "Manage IDE integrations and show status",
    "argumentHint": "[open]"
  },
  {
    "type": "prompt",
    "name": "init",
    "description": "Initialize a new CLAUDE.md file with codebase documentation",
    "contentLength": 0,
    "progressMessage": "analyzing your codebase",
    "source": "builtin"
  },
  {
    "name": "keybindings",
    "description": "Open or create your keybindings configuration file",
    "supportsNonInteractive": false,
    "type": "local"
  },
  {
    "type": "local-jsx",
    "name": "install-github-app",
    "description": "Set up Claude GitHub Actions for a repository",
    "availability": [
      "claude-ai",
      "console"
    ]
  },
  {
    "type": "local",
    "name": "install-slack-app",
    "description": "Install the Claude Slack app",
    "availability": [
      "claude-ai"
    ],
    "supportsNonInteractive": false
  },
  {
    "type": "local-jsx",
    "name": "mcp",
    "description": "Manage MCP servers",
    "immediate": true,
    "argumentHint": "[enable|disable [server-name]]"
  },
  {
    "type": "local-jsx",
    "name": "memory",
    "description": "Edit Claude memory files"
  },
  {
    "type": "local-jsx",
    "name": "mobile",
    "aliases": [
      "ios",
      "android"
    ],
    "description": "Show QR code to download the Claude mobile app"
  },
  {
    "type": "local-jsx",
    "name": "model",
    "description": "Set the AI model for Claude Code (currently deepseek-chat)",
    "argumentHint": "[model]",
    "immediate": false
  },
  {
    "type": "local-jsx",
    "name": "output-style",
    "description": "Deprecated: use /config to change output style",
    "isHidden": true
  },
  {
    "type": "local-jsx",
    "name": "remote-env",
    "description": "Configure the default remote environment for teleport sessions",
    "isHidden": true
  },
  {
    "type": "local-jsx",
    "name": "plugin",
    "aliases": [
      "plugins",
      "marketplace"
    ],
    "description": "Manage Claude Code plugins",
    "immediate": true
  },
  {
    "type": "prompt",
    "name": "pr-comments",
    "description": "Get comments from a GitHub pull request",
    "progressMessage": "fetching PR comments",
    "contentLength": 0,
    "source": "builtin"
  },
  {
    "description": "View release notes",
    "name": "release-notes",
    "type": "local",
    "supportsNonInteractive": true
  },
  {
    "type": "local",
    "name": "reload-plugins",
    "description": "Activate pending plugin changes in the current session",
    "supportsNonInteractive": false
  },
  {
    "type": "local-jsx",
    "name": "rename",
    "description": "Rename the current conversation",
    "immediate": true,
    "argumentHint": "[name]"
  },
  {
    "type": "local-jsx",
    "name": "resume",
    "description": "Resume a previous conversation",
    "aliases": [
      "continue"
    ],
    "argumentHint": "[conversation id or search term]"
  },
  {
    "type": "local-jsx",
    "name": "session",
    "aliases": [
      "remote"
    ],
    "description": "Show remote session URL and QR code",
    "isHidden": true
  },
  {
    "type": "local-jsx",
    "name": "skills",
    "description": "List available skills"
  },
  {
    "type": "local-jsx",
    "name": "stats",
    "description": "Show your Claude Code usage statistics and activity"
  },
  {
    "type": "local-jsx",
    "name": "status",
    "description": "Show Claude Code status including version, model, account, API connectivity, and tool statuses",
    "immediate": true
  },
  {
    "type": "prompt",
    "description": "Set up Claude Code's status line UI",
    "contentLength": 0,
    "aliases": [],
    "name": "statusline",
    "progressMessage": "setting up statusLine",
    "allowedTools": [
      "Agent",
      "Read(~/**)",
      "Edit(~/.claude/settings.json)"
    ],
    "source": "builtin",
    "disableNonInteractive": true
  },
  {
    "type": "local",
    "name": "stickers",
    "description": "Order Claude Code stickers",
    "supportsNonInteractive": false
  },
  {
    "type": "local-jsx",
    "name": "tag",
    "description": "Toggle a searchable tag on the current session",
    "argumentHint": "<tag-name>"
  },
  {
    "type": "local-jsx",
    "name": "theme",
    "description": "Change the theme"
  },
  {
    "aliases": [
      "bug"
    ],
    "type": "local-jsx",
    "name": "feedback",
    "description": "Submit feedback about Claude Code",
    "argumentHint": "[report]"
  },
  {
    "type": "prompt",
    "name": "review",
    "description": "Review a pull request",
    "progressMessage": "reviewing pull request",
    "contentLength": 0,
    "source": "builtin"
  },
  {
    "type": "local-jsx",
    "name": "ultrareview",
    "description": "~10–20 min · Finds and verifies bugs in your branch. Runs in Claude Code on the web. See https://code.claude.com/docs/en/claude-code-on-the-web"
  },
  {
    "description": "Restore the code and/or conversation to a previous point",
    "name": "rewind",
    "aliases": [
      "checkpoint"
    ],
    "argumentHint": "",
    "type": "local",
    "supportsNonInteractive": false
  },
  {
    "type": "prompt",
    "name": "security-review",
    "description": "Complete a security review of the pending changes on the current branch",
    "progressMessage": "analyzing code changes for security risks",
    "contentLength": 0,
    "source": "builtin"
  },
  {
    "type": "local-jsx",
    "name": "terminal-setup",
    "description": "Install Shift+Enter key binding for newlines",
    "isHidden": true
  },
  {
    "type": "local-jsx",
    "name": "upgrade",
    "description": "Upgrade to Max for higher rate limits and more Opus",
    "availability": [
      "claude-ai"
    ]
  },
  {
    "type": "local-jsx",
    "name": "extra-usage",
    "description": "Configure extra usage to keep working when limits are hit"
  },
  {
    "type": "local",
    "name": "extra-usage",
    "supportsNonInteractive": true,
    "description": "Configure extra usage to keep working when limits are hit",
    "isHidden": false
  },
  {
    "type": "local-jsx",
    "name": "rate-limit-options",
    "description": "Show options when rate limit is reached",
    "isHidden": true
  },
  {
    "type": "local-jsx",
    "name": "usage",
    "description": "Show plan usage limits",
    "availability": [
      "claude-ai"
    ]
  },
  {
    "type": "prompt",
    "name": "insights",
    "description": "Generate a report analyzing your Claude Code sessions",
    "contentLength": 0,
    "progressMessage": "analyzing your sessions",
    "source": "builtin"
  },
  {
    "name": "vim",
    "description": "Toggle between Vim and Normal editing modes",
    "supportsNonInteractive": false,
    "type": "local"
  },
  {
    "type": "local-jsx",
    "name": "think-back",
    "description": "Your 2025 Claude Code Year in Review"
  },
  {
    "type": "local",
    "name": "thinkback-play",
    "description": "Play the thinkback animation",
    "isHidden": true,
    "supportsNonInteractive": false
  },
  {
    "type": "local-jsx",
    "name": "permissions",
    "aliases": [
      "allowed-tools"
    ],
    "description": "Manage allow & deny tool permission rules"
  },
  {
    "type": "local-jsx",
    "name": "plan",
    "description": "Enable plan mode or view the current session plan",
    "argumentHint": "[open|<description>]"
  },
  {
    "type": "local-jsx",
    "name": "privacy-settings",
    "description": "View and update your privacy settings"
  },
  {
    "type": "local-jsx",
    "name": "hooks",
    "description": "View hook configurations for tool events",
    "immediate": true
  },
  {
    "type": "local-jsx",
    "name": "export",
    "description": "Export the current conversation to a file or clipboard",
    "argumentHint": "[filename]"
  },
  {
    "name": "sandbox",
    "description": "◯ sandbox disabled (⏎ to configure)",
    "argumentHint": "exclude \"command pattern\"",
    "isHidden": false,
    "immediate": true,
    "type": "local-jsx"
  },
  {
    "type": "local-jsx",
    "name": "logout",
    "description": "Sign out from your Anthropic account"
  },
  {
    "type": "local-jsx",
    "name": "login",
    "description": "Sign in with your Anthropic account"
  },
  {
    "type": "local-jsx",
    "name": "passes",
    "description": "Share a free week of Claude Code with friends",
    "isHidden": true
  },
  {
    "type": "local-jsx",
    "name": "tasks",
    "aliases": [
      "bashes"
    ],
    "description": "List and manage background tasks"
  }
]
`

const internalOnlyCommandsJSON = `[
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "type": "prompt",
    "name": "commit",
    "description": "Create a git commit",
    "allowedTools": [
      "Bash(git add:*)",
      "Bash(git status:*)",
      "Bash(git commit:*)"
    ],
    "contentLength": 0,
    "progressMessage": "creating commit",
    "source": "builtin"
  },
  {
    "type": "prompt",
    "name": "commit-push-pr",
    "description": "Commit, push, and open a PR",
    "allowedTools": [
      "Bash(git checkout --branch:*)",
      "Bash(git checkout -b:*)",
      "Bash(git add:*)",
      "Bash(git status:*)",
      "Bash(git push:*)",
      "Bash(git commit:*)",
      "Bash(gh pr create:*)",
      "Bash(gh pr edit:*)",
      "Bash(gh pr view:*)",
      "Bash(gh pr merge:*)",
      "ToolSearch",
      "mcp__slack__send_message",
      "mcp__claude_ai_Slack__slack_send_message"
    ],
    "contentLength": 3360,
    "progressMessage": "creating commit and PR",
    "source": "builtin"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "type": "prompt",
    "name": "init-verifiers",
    "description": "Create verifier skill(s) for automated verification of code changes",
    "contentLength": 0,
    "progressMessage": "analyzing your project and creating verifier skills",
    "source": "builtin"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "type": "local",
    "name": "bridge-kick",
    "description": "Inject bridge failure states for manual recovery testing",
    "supportsNonInteractive": false
  },
  {
    "type": "local",
    "name": "version",
    "description": "Print the version this session is running (not what autoupdate downloaded)",
    "supportsNonInteractive": true
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "isHidden": true,
    "name": "stub"
  },
  {
    "name": "agents-platform",
    "type": "local"
  },
  {
    "isHidden": true,
    "name": "stub"
  }
]
`
